# See https://pre-commit.com/
#
# Install pre-commit      with: `pip install pre-commit`
# Install pre-commit hook with: `pre-commit install`
#
# Run pre-commit locally with: `pre-commit run -a`
# Run pre-push   locally with: `pre-commit run -a --hook-stage push`
#
# Don't forget to run a dev-stack for successful testing.
# To disable a test, comment it.

files: ^src/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker   # Prevents weird UTF-8 encoding edge cases
      - id: check-case-conflict     # Check if case-insensitive filesystems would bork
      - id: check-executables-have-shebangs
      - id: check-toml              # Checks for valid TOML
      - id: check-json              # Checks for valid JSON
      - id: check-merge-conflict    # Checks strings that look like a committed merge conflict
      - id: check-xml               # Checks for valid XML
      - id: check-yaml              # Checks for valid YAML
      - id: mixed-line-ending       # Consistent LF or CRLF

  # Perform black reformatting for us
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        exclude: tests/
        # do not include the --check, so that it reformats the files for us.
        # args: [--check]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            # 'flake8-blind-except',
            # 'flake8-docstrings',
            # 'flake8-bugbear',
            # 'flake8-comprehensions',
            'flake8-implicit-str-concat',
            'pydocstyle>=5.0.0',
        ]
        args: [ "--ignore=E501,W292,W293,W503,W291" ]
        exclude: .venv
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
        files: \.(py|sh|rst|yml|yaml)$

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.0.0'  # Use the sha / tag you want to point at
      hooks:
      -   id: mypy
          args: [ --install-types, --non-interactive ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.258'
    hooks:
      # config is taken from the pyproject.toml file 
    - id: ruff
      
      
      # not enabling auto fix now, not sure what it can fix
      #args: [--fix, --exit-non-zero-on-fix, --ignore, "W292,W293,W291" ]


